import jwt from  ('jsonwebtoken');

const auth=(req,res,next)=>{
   try {
    const token=req.headers.authorization.split(" ")[1];//getting token from frontend
    const isCustomAuth=token.length<500;//cheking if token is generated by custom jwt auth or GOOGLE auth

    let decodedData;

    if(token&&isCustomAuth){//for custom-token
      decodedData=jwt.verify(token,'test');
      req.userId=decodedData?.id;
    }
    else{//for google-token
       decodedData=jwt.decode(token);
       req.userId=decodedData?.sub;//sub is the unique id per user
    }
      next();//we put auth in routes...next() method will be called after
      // above middleware auth logic successfully fullfilled
      //for ex-->when user want to like post he/she has to get through the auth middleware logic.

   } catch (error) {
    console.log(error)
   }
}
   export default auth;